### ISSUE TITLE
Clean up fingerprintGraph.py

### ISSUE THREAD

**Issue by Mibblez** [MartinNowak96/Neuromorphic-Data-Processing#5]
* Change file name to snake case
 * Remove reliance on the config file (only used here for the reconstruction window)
   * Allow the user to pass in either a number or the path to a config.json file. Make sure both are not passed in at the same time
   * Can probably remove variable declarations for hz, voltage, waveform, and degrees at the start of main after this is done
* In regex from lines 90-116, check to see if group is None instead of using try except
   * Make a variable for the regex group and then use a ternary to get the match if it isn't None
* Use a ternary for the if statement lines 123-125
* Remove save_fig from plot_event_count definition. We should always be saving the figure
    * Might run into issues overwriting old graphs. Make sure to check if a graph with the same name exists. If so, add a number to the end of the new graph to avoid the conflict

**Comment by nykash** [comment]
Solved by pull request #6 @Mibblez
